export const DEMO_VO_PAYLOAD = {
  account: {
    accountLabel: 'Demo Hardware Co., Ltd.',
    accountType: 'MAIN_ACCOUNT',
    permissions: ['PRODUCT_VIEW', 'INQUIRY_VIEW', 'SOURCING_VIEW'],
    lastLoginDetectedAt: new Date().toISOString(),
  },
  products: [
    {
      micProductId: 'P1001',
      productName: 'Aluminum Casement Window Handle',
      productUrl: 'https://demo-hardware.en.made-in-china.com/product/P1001/window-handle.html',
      model: 'WH-01',
      category: 'Window Hardware',
      status: 'ONLINE',
      keywords: ['window handle'],
      attributes: {},
      tradeInfo: '',
      isFeaturedProduct: true,
      featuredScore: 80,
      mainProductScore: 80,
      updatedAtRemote: '2026-08-01',
      syncedAt: new Date().toISOString(),
      rawSourceHash: 'demo-p1001',
      idConfidence: 0.95,
      source: 'MIC_VIRTUAL_OFFICE',
      evidenceLevel: 'VERIFIED',
    },
  ],
  inquiries: [],
  opportunities: {
    newInquiries: 0,
    unrepliedInquiries: 0,
    highIntentInquiries: 0,
    followUpNeeded: 0,
    newBuyers: 0,
    productInterestRanking: [],
    countryDistribution: [],
    syncedAt: new Date().toISOString(),
    evidenceLevel: 'VERIFIED',
  },
  sourcingRequests: [],
  syncMeta: {
    mode: 'MANUAL',
    modules: [{ module: 'PRODUCT_MANAGEMENT', status: 'SUCCESS', records: [] }],
    startedAt: new Date().toISOString(),
    source: 'FIXTURE',
  },
};
