export const PRODUCTION_ERROR_CODES = [
  'MIC_SESSION_EXPIRED',
  'MIC_PERMISSION_DENIED',
  'MIC_PAGE_CHANGED',
  'MIC_PARSE_FAILED',
  'MIC_LIVE_SYNC_FAILED',
  'MIC_FIXTURE_FORBIDDEN',
  'MIC_WRITE_BLOCKED',
  'MIC_MOCK_MIXIN',
  'AI_PROVIDER_FAILED',
  'AI_FACT_GUARD_FAIL',
  'DATABASE_FAILED',
  'QUEUE_FAILED',
  'RATE_LIMITED',
  'BACKUP_FAILED',
  'PARSER_ACCURACY_ABORT',
] as const;

export type ProductionErrorCode = (typeof PRODUCTION_ERROR_CODES)[number];

export const LIVE_SYNC_FAILED_MESSAGE = '真实数据同步失败';
export const MIC_DOM_CHANGED_MESSAGE = 'MIC 页面结构可能发生变化，请检查解析器。';
