import type { MICVirtualOfficeData } from '@trade-ai/shared-types';

/** Synthetic fixture payload — not real customer data. */
export const DEMO_VO_PAYLOAD: MICVirtualOfficeData = {
  account: {
    accountLabel: 'Demo Hardware Co., Ltd.',
    accountType: 'MAIN_ACCOUNT',
    permissions: ['PRODUCT_VIEW', 'INQUIRY_VIEW', 'SOURCING_VIEW'],
    lastLoginDetectedAt: new Date().toISOString(),
  },
  products: [
    {
      micProductId: 'P1001',
      productName: 'Aluminum Casement Window Handle',
      productUrl: 'https://demo-hardware.en.made-in-china.com/product/P1001/window-handle.html',
      model: 'WH-01',
      category: 'Window Hardware',
      status: 'ONLINE',
      keywords: ['window handle', 'casement'],
      attributes: {},
      tradeInfo: '',
      isFeaturedProduct: true,
      featuredScore: 80,
      mainProductScore: 80,
      updatedAtRemote: '2026-08-01',
      syncedAt: new Date().toISOString(),
      rawSourceHash: 'demo-p1001',
      idConfidence: 0.95,
      source: 'MIC_VIRTUAL_OFFICE',
      evidenceLevel: 'VERIFIED',
    },
  ],
  inquiries: [
    {
      micInquiryId: 'INQ2001',
      subject: 'Need window handle OEM for residential project',
      buyerName: 'Alex Buyer',
      buyerCompany: 'Nordic Doors AB',
      buyerCountry: 'Sweden',
      productId: 'P1001',
      productName: 'Aluminum Casement Window Handle',
      receivedAt: '2026-08-29T08:00:00.000Z',
      status: 'unreplied',
      assignedAccount: 'UNKNOWN',
      messagePreview: 'We need 5000 pcs OEM window handles, lead time 30 days, ISO mentioned.',
      lastReplyAt: null,
      syncedAt: new Date().toISOString(),
      idConfidence: 0.95,
      source: 'MIC_VIRTUAL_OFFICE',
      evidenceLevel: 'VERIFIED',
    },
  ],
  opportunities: {
    newInquiries: 1,
    unrepliedInquiries: 1,
    highIntentInquiries: 1,
    followUpNeeded: 0,
    newBuyers: 1,
    productInterestRanking: [{ productName: 'Aluminum Casement Window Handle', count: 1 }],
    countryDistribution: [{ country: 'Sweden', count: 1 }],
    syncedAt: new Date().toISOString(),
    evidenceLevel: 'VERIFIED',
  },
  sourcingRequests: [
    {
      micRequestId: 'RFQ3001',
      title: 'Window handle for residential casement windows',
      category: 'Window Hardware',
      country: 'Germany',
      quantity: '8000',
      unit: 'pcs',
      publishedAt: '2026-08-15',
      deadline: '2026-09-15',
      status: 'open',
      matchingProducts: [],
      syncedAt: new Date().toISOString(),
      idConfidence: 0.9,
      source: 'MIC_VIRTUAL_OFFICE',
      evidenceLevel: 'VERIFIED',
    },
  ],
  syncMeta: {
    mode: 'MANUAL',
    modules: [
      { module: 'PRODUCT_MANAGEMENT', status: 'SUCCESS', records: [] },
      { module: 'INQUIRIES', status: 'SUCCESS', records: [] },
      { module: 'SOURCING', status: 'SUCCESS', records: [] },
    ],
    startedAt: new Date().toISOString(),
    source: 'FIXTURE',
  },
};
