export const MIC_HOST_PATTERN = /(^|\.)made-in-china\.com$/i;

export const MIC_PRODUCT_URL_PATTERNS = [
  /\/product[-_]?detail/i,
  /\/product\//i,
  /\/showroom\/.+\/product/i,
  /_p\.html/i,
  /\/prod\//i,
];

export const MIC_SHOP_URL_PATTERNS = [
  /\/company/i,
  /\/showroom\/?$/i,
  /\/factory/i,
  /\/about/i,
  /\.en\.made-in-china\.com\/?$/i,
];

export const MIC_SELECTORS = {
  productName: [
    'h1[itemprop="name"]',
    'h1.pro-name',
    'h1.product-name',
    'h1.sr-pro-name',
    '.sr-proMainInfo h1',
    '.pro-name h1',
    '[class*="product"][class*="name"] h1',
    '[class*="title"] h1',
    'h1',
    '[itemprop="name"]',
    '.product-name',
    '.pro-name',
    '.sr-pro-name',
  ],
  companyName: [
    '[itemprop="brand"]',
    '[itemprop="manufacturer"]',
    '.company-name a',
    '.company-name',
    '.com-name a',
    '.com-name',
    '.sr-com-name',
    '.supplier-name a',
    '.supplier-name',
    'a[href*="/company"]',
    'a[href*="showroom"][class*="name"]',
    'a[href*=".en.made-in-china.com/"][class*="com"]',
    '.company-info .name',
  ],
  description: [
    '[itemprop="description"]',
    '#productDescription',
    '.product-description',
    '.pro-desc',
    '.detail-desc',
    '.prod-desc',
    '[class*="product"][class*="desc"]',
    '.J-rich-text',
    '.rich-text',
    '#richDesc',
  ],
  descriptionHeadings: [
    'h2',
    'h3',
    'h4',
    '.tit',
    '.title',
    '[class*="section"] [class*="title"]',
  ],
  images: [
    '.sr-proImg img',
    '.pro-img img',
    '.product-img img',
    '.preview-img img',
    '.pic-box img',
    '.J-pic-list img',
    '.pic-list img',
    '[class*="gallery"] img',
    '[class*="swiper"] img',
    '.magic-zoom img',
    '[itemprop="image"]',
  ],
  specTables: [
    '.basic-info table',
    '.prod-prop table',
    '.obj-info table',
    '.spec-table',
    '.product-attr table',
    '.pro-attr table',
    '[class*="basic"][class*="info"] table',
    '[class*="parameter"] table',
    '[class*="spec"] table',
    'table[class*="attr"]',
    'table',
  ],
  specLists: [
    '.basic-info dl',
    '.prod-prop dl',
    '[class*="spec"] dl',
    '.basic-info li',
    '.prod-prop li',
  ],
  category: [
    'nav.breadcrumb',
    '.breadcrumb',
    '.cate-path',
    '.crumbs',
    '[class*="breadcrumb"]',
    '[itemprop="category"]',
  ],
  moq: [
    '[class*="moq"]',
    '[data-role="moq"]',
    '.trade-info td',
    '.basic-info td',
  ],
  delivery: [
    '.delivery-time',
    '.lead-time',
    '[class*="lead-time"]',
    '[class*="delivery"]',
  ],
};
