import { detectCoreProductTerm } from '@trade-ai/scoring-rules';
import { emptyPageData } from '@trade-ai/shared-types';
import type { PlatformPageData } from '@trade-ai/shared-types';
import type { AiRuntimeConfig } from '../config';
import type {
  GenerateStructuredInput,
  GenerateStructuredResult,
  GenerateTextInput,
  GenerateTextResult,
  HealthCheckResult,
  LLMProvider,
  LlmAnalyzeResult,
} from '../provider';

export class MockLLMProvider implements LLMProvider {
  readonly name: string = 'mock';

  constructor(private readonly config?: AiRuntimeConfig) {}

  async generateText(input: GenerateTextInput): Promise<GenerateTextResult> {
    return {
      text: `[mock:${this.name}] ${input.prompt.slice(0, 80)}`,
      model: 'mock',
      usage: { inputTokens: 0, outputTokens: 0 },
    };
  }

  async generateStructured(input: GenerateStructuredInput): Promise<GenerateStructuredResult> {
    const title = this.extractField(input.prompt, 'productName') || 'Product';
    const page = emptyPageData({
      productName: title,
      title,
      platform: 'MADE_IN_CHINA',
      pageType: 'MIC_PRODUCT_EDIT',
    });
    const detected = detectCoreProductTerm(page).coreProductTerm;
    const core =
      /\bvacuum cleaner\b/i.test(title)
        ? 'vacuum cleaner'
        : detected || 'product';
    const data = {
      originalTitle: title,
      coreProductTerm: core,
      problems: ['Mock provider: no live LLM key', 'Title may lack buyer-intent phrasing'],
      recommendedTitles: [
        {
          style: 'SEO_BALANCED',
          title: `${title}`.slice(0, 120),
          reason: 'Keep the original facts and a readable English order.',
          usedFacts: [title],
          warnings: ['Generated by MockProvider'],
        },
        {
          style: 'BUYER_INTENT',
          title: `${core} for Industrial Use`.slice(0, 120),
          reason: 'Lead with the product noun buyers search.',
          usedFacts: [core],
          warnings: ['Generated by MockProvider'],
        },
        {
          style: 'GEO_FRIENDLY',
          title: `Industrial ${core}`.slice(0, 120),
          reason: 'Short entity-clear title for AI citation.',
          usedFacts: [core],
          warnings: ['Generated by MockProvider'],
        },
      ],
      keywordSuggestions: [core, 'industrial cleaner', 'wet dry vacuum'].slice(0, 3),
    };
    return {
      data,
      raw: JSON.stringify(data),
      model: 'mock',
      usage: { inputTokens: 0, outputTokens: 0 },
      repaired: false,
    };
  }

  async healthCheck(): Promise<HealthCheckResult> {
    return {
      ok: true,
      provider: 'mock',
      model: 'mock',
      latencyMs: 0,
      status: 'mock',
      error: this.config?.fallbackReason,
    };
  }

  async analyze(pageData: PlatformPageData): Promise<LlmAnalyzeResult> {
    return {
      summary: `Mock analysis for ${pageData.productName || pageData.title || 'unknown page'}. Provider=${this.name}.`,
      suggestions: [
        'Clarify the product focus keyword in the title.',
        'Add structured specifications and OEM capability.',
        'Publish FAQ and application scenarios for GEO.',
      ],
    };
  }

  private extractField(prompt: string, field: string): string {
    const m = prompt.match(new RegExp(`${field}:\\s*(.+)`));
    return m?.[1]?.trim() && m[1] !== '(none)' ? m[1].trim() : '';
  }
}
